# docker-compose.yml

version: "3.7"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - backend-db:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      FRONTEND_URL: http://localhost:8080
    depends_on:
      - postgres
    ports:
      - '3000:3000'

  frontend:
    build: ./frontend
    container_name: dashboard-ui
    env_file: frontend/.env
    depends_on:
      - backend
    ports:
      - '8080:8080'

volumes:
  backend-db:




